global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'hearmate'
    static_configs:
      - targets: ['hearmate:9000']

  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']
